spring:
  application:
  name: orders
  config:
    import: "optional:classpath:.env"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_ORDERS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080